# Generated by Django 5.2.6 on 2025-11-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('ocupacao_profissional', models.CharField(max_length=255, verbose_name='Ocupação profissional')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('numero', models.CharField(max_length=15, verbose_name='Número')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('numero_contato', models.CharField(max_length=15, verbose_name='Telefone para contato')),
                ('foi_lar_temporario', models.BooleanField(default=False, verbose_name='Você já foi lar temporário antes?')),
                ('disponibilidade_inicio', models.DateField(verbose_name='Informe uma data em que se inicia a sua disponibilidade para ser lar temporário de um bichinho')),
                ('animal_externo', models.TextField(verbose_name='Você tem outros animais em casa? Se sim, quantos e quais?\xa0\xa0Caso ele tenha alguma condição como FIV, FELV, esporotricose etc, nos informe aqui também!')),
                ('mora_casa', models.BooleanField(default=False, verbose_name='Mora em casa?')),
                ('restrito', models.BooleanField(default=False, verbose_name='O animal ficará restrito em alguma parte da casa?')),
                ('estrutura', models.CharField(max_length=20, verbose_name='Você tem estrutura segura para gatos (telas nas janelas, ambiente fechado etc)?')),
                ('custos', models.CharField(max_length=50, verbose_name='Você pode ajudar com os custos (ração, areia, etc), ou prefere que a Resgatando vidas 4 patas cubra?')),
                ('duracao_aproximada', models.CharField(max_length=20, verbose_name='Por quanto tempo, aproximadamente, você conseguiria manter um animalzinho sob seus cuidados?\xa0\xa0')),
                ('visita', models.CharField(max_length=50, verbose_name='Caso haja um adotante interessado em visitar o animalzinho, você poderá recebê-lo?')),
                ('informacao_adicional', models.TextField(blank=True, null=True, verbose_name='Alguma observação ou informação que gostaria de adicionar?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatos.gato', verbose_name='Gato')),
            ],
            options={
                'verbose_name': 'Lar Temporário',
                'verbose_name_plural': 'Lares Temporários',
                'db_table': 'lar_temporario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoLarTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.gato', verbose_name='Gato')),
                ('lar_temporario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lares_temporarios.lartemporario', verbose_name='Lar temporário')),
            ],
            options={
                'verbose_name': 'Histórico de Lar Temporário',
                'verbose_name_plural': 'Históricos de Lares Temporários',
                'db_table': 'historico_lar_temporario',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LarTemporarioAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.gato', verbose_name='Gato')),
                ('lar_temporario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lares_temporarios.lartemporario', verbose_name='Lar temporário')),
            ],
            options={
                'verbose_name': 'Lar Temporario Atual',
                'verbose_name_plural': 'Lares Temporários Atuais',
                'db_table': 'lar_temporario_atual',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
