# Generated by Django 5.2.6 on 2025-11-24 22:19

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('vermifugado', models.BooleanField(default=False, verbose_name='Vermifugado')),
                ('cuidado_especial', models.BooleanField(default=False, verbose_name='Cuidado especial')),
                ('fiv_negativo', models.BooleanField(default=False, verbose_name='FIV negativo')),
                ('fiv_positivo', models.BooleanField(default=False, verbose_name='FIV positivo')),
                ('felv_negativo', models.BooleanField(default=False, verbose_name='FeLV negativo')),
                ('felv_positivo', models.BooleanField(default=False, verbose_name='FeLV positivo')),
            ],
            options={
                'verbose_name': 'Cuidado',
                'verbose_name_plural': 'Cuidados',
                'db_table': 'cuidado',
            },
        ),
        migrations.CreateModel(
            name='Moradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_com_quintal', models.BooleanField(default=False, verbose_name='Casa com quintal')),
                ('apartamento', models.BooleanField(default=False, verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Moradia',
                'verbose_name_plural': 'Moradias',
                'db_table': 'moradia',
            },
        ),
        migrations.CreateModel(
            name='Sociavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatos', models.BooleanField(default=False, verbose_name='gatos')),
                ('desconhecidos', models.BooleanField(default=False, verbose_name='desconhecidos')),
                ('cachorros', models.BooleanField(default=False, verbose_name='cachorros')),
                ('criancas', models.BooleanField(default=False, verbose_name='crianças')),
                ('nao_sociavel', models.BooleanField(default=False, verbose_name='Não sociável')),
            ],
            options={
                'verbose_name': 'Socialização',
                'verbose_name_plural': 'Socializações',
                'db_table': 'sociavel',
            },
        ),
        migrations.CreateModel(
            name='Temperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docil', models.BooleanField(default=False, verbose_name='Dócil')),
                ('agressivo', models.BooleanField(default=False, verbose_name='Agressivo')),
                ('calmo', models.BooleanField(default=False, verbose_name='Calmo')),
                ('brincalhao', models.BooleanField(default=False, verbose_name='Brincalhão')),
                ('arisco', models.BooleanField(default=False, verbose_name='Arisco')),
                ('independente', models.BooleanField(default=False, verbose_name='Independente')),
                ('carente', models.BooleanField(default=False, verbose_name='Carente')),
            ],
            options={
                'verbose_name': 'Temperamento',
                'verbose_name_plural': 'Temperamentos',
                'db_table': 'temperamento',
            },
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do gato')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('descricao', models.TextField(max_length=10000, verbose_name='Sobre o gato')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('lar_temporario', models.BooleanField(default=False, verbose_name='Precisa de lar temporário')),
                ('adotado', models.BooleanField(default=False, verbose_name='Adotado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cuidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.cuidado', verbose_name='Cuidados')),
                ('moradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.moradia', verbose_name='Moradia adequada')),
                ('sociavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.sociavel', verbose_name='Socialização')),
                ('temperamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.temperamento', verbose_name='Temperamento')),
            ],
            options={
                'verbose_name': 'Gato',
                'verbose_name_plural': 'Gatos',
                'db_table': 'gatos',
                'ordering': ['-created_at'],
            },
        ),
    ]
