# Generated by Django 5.2.6 on 2025-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0003_alter_gato_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='idade',
        ),
        migrations.AddField(
            model_name='gato',
            name='data_nascimento',
            field=models.DateField(default='2020-01-01', verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
